export const LOGIN_IS_SUBMITTING = 'LOGIN_IS_SUBMITTING';
export const LOGIN_HAS_ERRORED = 'LOGIN_HAS_ERRORED';
export const LOGIN_SUBMIT_SUCCESS = 'LOGIN_SUBMIT_SUCCESS';

export const SALARIES = 'SALARIES';
export const RATECARD = 'RATECARD';
export const SALARIES_IS_LOADING = 'SALARIES_IS_LOADING';
export const SALARIES_HAS_ERRORED = 'SALARIES_HAS_ERRORED';

export const PROJECTS = 'PROJECTS';
export const PROJECTS_IS_LOADING = 'PROJECTS_IS_LOADING';
export const PROJECTS_HAS_ERRORED = 'PROJECTS_HAS_ERRORED';

export const ACTIVITES = 'ACTIVITIES';
export const EFFICIENCY = 'EFFICIENCY';
export const SHORTEST_DAY = 'SHORTEST_DAY';
export const LONGEST_DAY = 'LONGEST_DAY';
export const TOTAL_HOURS = 'TOTAL_HOURS';
export const TOTAL_DAYS = 'TOTAL_DAYS';
export const AVERAGE_DAY = 'AVERAGE_DAY';
export const DAYS_OF_WEEK = 'DAYS_OF_WEEK';
export const ACTIVITY_HAS_ERRORED = 'ACTIVITY_HAS_ERRORED';
export const ACTIVITY_IS_LOADING = 'ACTIVITY_IS_LOADING';

export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const FIRSTNAME = 'FIRSTNAME';
export const LASTNAME = 'LASTNAME';
export const USERID = 'USERID';
export const TOKEN = 'TOKEN';
